### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by wileewang** [rinongal/StyleGAN-nada#20]
Hi! when I try to start training,  I ran into this problem:

***
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    train(args)
  File "train.py", line 86, in train
    [sampled_src, sampled_dst], loss = net(sample_z)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/pycharm_project_1/ZSSGAN/model/ZSSGAN.py", line 278, in forward
    clip_loss = torch.sum(torch.stack([self.clip_model_weights[model_name] * self.clip_loss_models[model_name](frozen_img, self.source_class, trainable_img, self.target_class) for model_name in self.clip_model_weights.keys()]))
  File "/mnt/pycharm_project_1/ZSSGAN/model/ZSSGAN.py", line 278, in <listcomp>
    clip_loss = torch.sum(torch.stack([self.clip_model_weights[model_name] * self.clip_loss_models[model_name](frozen_img, self.source_class, trainable_img, self.target_class) for model_name in self.clip_model_weights.keys()]))
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/pycharm_project_1/ZSSGAN/criteria/clip_loss.py", line 294, in forward
    clip_loss += self.lambda_direction * self.clip_directional_loss(src_img, source_class, target_img, target_class)
  File "/mnt/pycharm_project_1/ZSSGAN/criteria/clip_loss.py", line 175, in clip_directional_loss
    self.target_direction = self.compute_text_direction(source_class, target_class)
  File "/mnt/pycharm_project_1/ZSSGAN/criteria/clip_loss.py", line 113, in compute_text_direction
    source_features = self.get_text_features(source_class)
  File "/mnt/pycharm_project_1/ZSSGAN/criteria/clip_loss.py", line 97, in get_text_features
    text_features = self.encode_text(tokens).detach()
  File "/mnt/pycharm_project_1/ZSSGAN/criteria/clip_loss.py", line 73, in encode_text
    return self.model.encode_text(tokens)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/clip/model.py", line 344, in encode_text
    x = self.transformer(x)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/clip/model.py", line 199, in forward
    return self.resblocks(x)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/clip/model.py", line 186, in forward
    x = x + self.attention(self.ln_1(x))
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/clip/model.py", line 183, in attention
    return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0]
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 987, in forward
    attn_mask=attn_mask)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/functional.py", line 4790, in multi_head_attention_forward
    attn_output_weights = torch.bmm(q, k.transpose(1, 2))
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)` 

***
My environment is:
Python3.7
CUDA 11.1
cuDNN 8.0.5
Pytorch 1.8.1
Ubuntu 18.04

Do you have any ideas about this? Thanks for your help!

**Comment by rinongal** [comment]
How much GPU memory do you have, and what models are you running? We managed to fit things on a 1080 (~10GB). If you've got something similar, there might be some things you can play with to make it run on your machine.

**Comment by wileewang** [comment]
In addition, I have tried another combination of torch and cuda, like torch 1.7.1 + cuda 11.0, and I got more weird report:
```
No such file or directory #include <cublas_v2.h>
```
May I know your version of torch and cuda?
