### ISSUE TITLE
Local run issue

### ISSUE THREAD

**Issue by JPW0080** [rinongal/StyleGAN-nada#49]
After cloning https://huggingface.co/spaces/rinong/StyleGAN-NADA/tree/main

Attempting to run locally for video generation throws an error:

OS: Win 11 x64
CPU: 8700k
GPU: 3090
Ram: 32GB

Anaconda3 - python3.8:

conda activate chunkmogrify

cd C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA

python app.py

Browser:
http://127.0.0.1:7860/

After adding any image, and selecting Edit image:

Aligned image has shape: (256, 256)
Traceback (most recent call last):
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\gradio\routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\gradio\blocks.py", line 274, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "app.py", line 194, in inner
    return func(self, *args, edit_choices)
  File "app.py", line 231, in edit_image
    return self.predict(input, output_styles, edit_choices=edit_choices)
  File "app.py", line 252, in predict
    inverted_latent = self.invert_image(input)
  File "app.py", line 152, in invert_image
    images, latents = self.run_on_batch(transformed_image.unsqueeze(0))
  File "app.py", line 300, in run_on_batch
    images, latents = self.e4e_net(
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA\e4e\models\psp.py", line 61, in forward
    codes = self.encoder(x)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA\e4e\models\encoders\psp_encoders.py", line 174, in forward
    x = self.input_layer(x)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

The above Runetime Error also occured with: 

WSL2 - Ubuntu 20.04.4 LTS

Anaconda3 - python3.9

**Comment by rinongal** [comment]
It looks like something is still loading on the CPU despite the availability of a GPU.

Could you try adding the following line to app.py right after the initialization of the e4e encoder (e.g. somewhere near line 122)?
```
self.e4e_net.to(self.device)
```

Basically it should now look something like this:
```     
self.e4e_net = pSp(opts, self.device)
self.e4e_net.to(self.device)
self.e4e_net.eval()
```

**Comment by JPW0080** [comment]
The suggested edit/addition worked for all but the StyleCLIP option:

Anaconda3 Powershell Prompt:

conda activate chunkmogrify
cd C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA

python app.py

Browser:
http://127.0.0.1:7860/

Image UL:
StyleCLIP
Edit image:

Aligned image has shape: (256, 256)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 19.80it/s]
Traceback (most recent call last):
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\gradio\routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\gradio\blocks.py", line 274, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "app.py", line 195, in inner
    return func(self, *args, edit_choices)
  File "app.py", line 232, in edit_image
    return self.predict(input, output_styles, edit_choices=edit_choices)
  File "app.py", line 267, in predict
    img, _ = g_ema(latent_for_gen, input_is_s_code=True, input_is_latent=True, truncation=1, randomize_noise=False)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA\model\sg2_model.py", line 578, in forward
    return self.forward_with_s(styles, return_latents, noise, randomize_noise)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA\model\sg2_model.py", line 670, in forward_with_s
    out = self.conv1(out, styles, is_s_code=True, noise=noise[0])
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA\model\sg2_model.py", line 381, in forward
    out = self.conv(input, style, is_s_code=is_s_code)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\StyleGAN-NADA\model\sg2_model.py", line 275, in forward
    weight = self.scale * self.weight * style
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by rinongal** [comment]
I won't have time to debug this until the weekend. If I had to guess from from looking at that log, you might be able to resolve this by explicitly moving the latents to the GPU, i.e. adding:

```
for layer in latent_for_gen:
    latent_for_gen[layer] = latent_for_gen[layer].cuda()
```
Just before like 267 in app.py.

I'll have a closer look during the weekend and see if I can track down the source of the problem.

**Comment by JPW0080** [comment]
Gave it a go:

Image UL:
StyleCLIP
Edit image:


Aligned image has shape: (256, 256)
Traceback (most recent call last):
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\gradio\routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\gradio\blocks.py", line 274, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "app.py", line 195, in inner
    return func(self, *args, edit_choices)
  File "app.py", line 232, in edit_image
    return self.predict(input, output_styles, edit_choices=edit_choices)
  File "app.py", line 268, in predict
    latent_for_gen[layer] = latent_for_gen[layer].cuda()
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by JPW0080** [comment]
Disregard, my placement of the suggested code was incorrect.

It works.
